name: Build and Analyze
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Version
        id: vars
        run: |
          VERSION=v$(git rev-list --count HEAD)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Run Linter
        run: npm run lint

      - name: Run Tests and Coverage
        run: npm run test -- --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: -Dsonar.projectVersion=${{ env.VERSION }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/23_as221s5_t02_michigo:${{ env.VERSION }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/23_as221s5_t02_michigo:${{ env.VERSION }}
        
